#define TEST_COMMON_FILENAME "test_common_tools"
#define TEST_COMMON_LOCATION "/home/hal/.clion10/system/cmake/generated/92a3cc73/92a3cc73/Debug/tests/test_common_tools"
#define TEST_COMMON_DIRECTORY "/home/hal/.clion10/system/cmake/generated/92a3cc73/92a3cc73/Debug/tests"
#define CMAKE_SOURCE_DIR "/home/hal/git/common-tools"
#define CMAKE_CURENT_SOURCE_DIRECTORY "/home/hal/git/common-tools/tests"
#define CMAKE_CURRENT_BINARY_DIR "/home/hal/.clion10/system/cmake/generated/92a3cc73/92a3cc73/Debug/tests"
